import { DATABASE_MIGRATION_TABLE } from "../../src/db";

/** Reviewed redaction coverage, including historical columns needed by released fixtures. */
export const KNOWN_COLUMNS: Readonly<Record<string, ReadonlySet<string>>> = Object.fromEntries(
  Object.entries({
    _meta: ["key", "value"],
    accounts: [
      "id",
      "name",
      "color",
      "schedulingMode",
      "timezone",
      "weekStartsOn",
      "workingDays",
      "language",
      "disciplinesEnabled",
      "groupResourcesByEngagement",
      "placeholdersEnabled",
      "externalEnabled",
      "createdAt",
      "updatedAt",
      "internalColourMode",
      "showInternalProjects",
      "showInternalActivities",
      "inlineActivityCreateEnabled",
    ],
    clients: [
      "id",
      "accountId",
      "name",
      "color",
      "isPrivate",
      "codeName",
      "builtin",
      "archivedAt",
      "deletedAt",
      "createdAt",
      "updatedAt",
    ],
    disciplines: ["id", "accountId", "name", "color", "sortOrder", "createdAt", "updatedAt"],
    projects: [
      "id",
      "accountId",
      "name",
      "clientId",
      "color",
      "isPrivate",
      "codeName",
      "archivedAt",
      "deletedAt",
      "createdAt",
      "updatedAt",
    ],
    phases: ["id", "accountId", "name", "projectId", "createdAt", "updatedAt"],
    resources: [
      "id",
      "accountId",
      "kind",
      "name",
      "role",
      "disciplineId",
      "employmentType",
      "engagement",
      "halfDays",
      "isFavourite",
      "workingHoursPerDay",
      "workingDays",
      "projectId",
      "color",
      "archivedAt",
      "deletedAt",
      "createdAt",
      "updatedAt",
    ],
    activities: ["id", "accountId", "name", "kind", "projectId", "phaseId", "createdAt", "updatedAt"],
    tasks: ["id", "accountId", "name", "kind", "projectId", "phaseId", "createdAt", "updatedAt"],
    allocations: [
      "id",
      "accountId",
      "resourceId",
      "activityId",
      "taskId",
      "projectId",
      "seriesId",
      "startDate",
      "endDate",
      "hoursPerDay",
      "status",
      "note",
      "ignoreWeekends",
      "createdAt",
      "updatedAt",
    ],
    timeOff: ["id", "accountId", "resourceId", "startDate", "endDate", "type", "note", "createdAt", "updatedAt"],
    // Membership flags and scheduling settings/dates are deliberately retained.
    account_members: ["accountId", "userId", "role", "status", "createdAt", "signInConfirmed"],
    account_member_sign_in_tracking: ["accountId"],
    closures: ["id", "accountId", "name", "startDate", "endDate", "createdAt", "updatedAt"],
    capacitylens_federated_link_ceremonies: [
      "id",
      "principalId",
      "providerId",
      "createdAt",
      "expiresAt",
      "completedAt",
    ],
    capacitylens_federated_link_observations: [
      "accountRowId",
      "principalId",
      "providerId",
      "subject",
      "verifiedAt",
      "auditedAt",
    ],
    capacitylens_sso_cutover_state: ["applicationId", "activatedAt"],
    invites: ["tokenHash", "token", "id", "accountId", "role", "preauthEmail", "expiresAt", "usedAt", "createdAt"],
    user: ["id", "name", "email", "emailVerified", "image", "createdAt", "updatedAt", "twoFactorEnabled"],
    session: ["id", "expiresAt", "token", "createdAt", "updatedAt", "ipAddress", "userAgent", "userId"],
    account: [
      "id",
      "accountId",
      "providerId",
      "userId",
      "accessToken",
      "refreshToken",
      "idToken",
      "accessTokenExpiresAt",
      "refreshTokenExpiresAt",
      "scope",
      "password",
      "createdAt",
      "updatedAt",
    ],
    twoFactor: ["id", "secret", "backupCodes", "userId", "verified", "failedVerificationCount", "lockedUntil"],
    verification: ["id", "identifier", "value", "expiresAt", "createdAt", "updatedAt"],
    capacitylens_bootstrap_claim: ["id", "claimedAt", "claimToken"],
    account_security_revisions: ["principalId", "revision", "updatedAt"],
    account_commands: [
      "applicationId",
      "operation",
      "idempotencyKey",
      "commandId",
      "actorPrincipalId",
      "targetPrincipalId",
      "workspaceId",
      "payloadHash",
      "status",
      "resultJson",
      "failureCode",
      "createdAt",
      "updatedAt",
    ],
    account_session_assurance: ["sessionId", "principalId", "assurance", "providerId", "createdAt"],
    account_federated_provider_bindings: ["applicationId", "issuer", "providerId", "createdAt"],
    capacitylens_audit_outbox: ["sequence", "id", "payload", "createdAt"],
    capacitylens_sync_sessions: ["sessionId", "lastSequence", "updatedAt"],
    capacitylens_sync_row_provenance: ["tableName", "rowId", "accountId", "sessionId", "sequence", "rowHash"],
    [DATABASE_MIGRATION_TABLE]: ["version", "name", "checksum", "appliedAt"],
  }).map(([table, names]) => [table, new Set(names)]),
);
/** Tables whose columns have an explicit rehearsal redaction policy. */
export const KNOWN_TABLES: ReadonlySet<string> = new Set(Object.keys(KNOWN_COLUMNS));
