// i18n seam (P1.5.1) — Paraglide (inlang) compile-time, type-safe messages.
//
// WHY Paraglide: messages are compiled into typed functions (src/paraglide, generated + gitignored),
// so a removed/renamed key is a tsc/build error — not a runtime "missing translation" surprise. The
// message source of truth is committed (project.inlang/settings.json + messages/<locale>.json); the
// compiled output is regenerated by the package scripts (build/gate/test/dev all precompile).
//
// WHY this module exists: it is the SINGLE place the app reads the inlang runtime. Components import
// `m` from here (never from @/paraglide directly) so the generated path stays an implementation
// detail, and the locale<-account wiring lives in one documented spot. English-only today; the seam
// is ready for later locales without touching call sites.

import { m } from '@/paraglide/messages.js'
import { baseLocale, isLocale, setLocale, type Locale } from '@/paraglide/runtime.js'

/**
 * The compiled message catalogue — typed functions, one per key in messages/<locale>.json.
 *
 * Re-exported from the single i18n seam so call sites import `{ m }` from `@/i18n` rather than the
 * generated `@/paraglide` path. Each member is type-checked: deleting a key from the message source
 * (then recompiling) removes its function here and turns every `m.<key>()` call into a tsc error —
 * that compile-time safety IS the point of choosing Paraglide.
 */
export { m }

/**
 * Apply the active company's UI language to the i18n runtime.
 *
 * Reads {@link import('@capacitylens/shared/types').Account.language} (the per-account language seam)
 * and switches the Paraglide runtime to it. `language` is optional/free-form on the Account, so we
 * validate it through the generated {@link isLocale} guard and fall back to {@link baseLocale} ('en')
 * for an absent or unrecognised value — a bad stored value can never throw or blank the UI here.
 *
 * `reload: false` is deliberate: the locale is account-scoped and client-only (the Vite plugin uses
 * the `globalVariable` strategy, not a cookie), so switching must NOT trigger a page reload — React
 * re-renders pick up the new messages on the next render. English-only today; the resolve/validate
 * path is already correct for additional locales (P1.5.2+).
 *
 * @param language - The active Account's `language` field (e.g. `'en'`); `undefined` ⇒ baseLocale.
 */
export function syncLocaleFromAccount(language: string | undefined): void {
  const resolved: Locale = language !== undefined && isLocale(language) ? language : baseLocale
  // `setLocale` is typed `void | Promise<void>` (it becomes async only if a custom async strategy is
  // configured). Our strategies — `globalVariable`/`baseLocale` — are synchronous, so there is nothing
  // to await; `void` marks the non-promise return intentionally ignored (the repo's floating-promise
  // discipline) rather than mislabelling this as async.
  void setLocale(resolved, { reload: false })
}
