export const STATIC_SPA_ROUTES = [
  "overview",
  "resources",
  "external",
  "disciplines",
  "clients",
  "projects",
  "activities",
  "timeoff",
  "team",
  "settings",
  "diagnostics",
  "account",
  "help",
  "verify-microsoft",
];
